// DO NOT edit this file, it is generated automatically
export enum tag {
  COSE_Encrypt0 = 16,
  COSE_Mac0 = 17,
  COSE_Sign1 = 18,
  COSE_Countersignature = 19,
  COSE_Encrypt = 96,
  COSE_Mac = 97,
  COSE_Sign = 98,
}