// DO NOT edit this file, it is generated automatically
/**  
 * @see {@link https://www.iana.org/assignments/jose}  
 */ 


export type key_type = 'EC' | 'OKP' | 'RSA' | 'oct'
export type key_use = 'enc' | 'sig';
export type key_ops = 'sign' | 'verify' | 'encrypt' | 'decrypt' | 'wrapKey' | 'unwrapKey' | 'deriveKey' | 'deriveBits';

/**
 * Common JSON Web Key Parameters
 * @enum {string}
 */
export const web_key = {
  'kty' : 'kty',
  'use' : 'use',
  'key_ops' : 'key_ops',
  'alg' : 'alg',
  'kid' : 'kid',
  'x5u' : 'x5u',
  'x5c' : 'x5c',
  'x5t' : 'x5t',
  'x5t#S256' : 'x5t#S256',
  'ext' : 'ext',
  'iat' : 'iat',
  'nbf' : 'nbf',
  'exp' : 'exp',
  'revoked' : 'revoked',
} as const


export type web_key_type = {
  'kty' : key_type,
  'use' ?: key_use,
  'key_ops' ?: key_ops,
  'alg' ?: string,
  'kid' ?: string,
  'x5u' ?: string,
  'x5c' ?: string[],
  'x5t' ?: string,
  'x5t#S256' ?: string,
  'ext' ?: boolean,
  'iat' ?: number,
  'nbf' ?: number,
  'exp' ?: number,
  'revoked' ?: {
    revoked_at: number,
    reason?: string,
  },
}

/**
 * EC Parameters
 * @enum {string}
 */
export const ec_web_key  = {
  ...web_key,
  'crv' : 'crv',
  'x' : 'x',
  'y' : 'y',
  'd' : 'd',
} as const

export type public_ec_web_key_type = web_key_type &  {
  crv: string,
  x: string,
  y: string,
}
export type private_ec_web_key_type = public_ec_web_key_type & {
  d: string,
}

export const private_ec_web_key_params = {
  d: "p",
}

/**
 * RSA Parameters
 * @enum {string}
 */
export const rsa_web_key  = {
  ...web_key,
  'n' : 'n',
  'e' : 'e',
  'd' : 'd',
  'p' : 'p',
  'q' : 'q',
  'dp' : 'dp',
  'dq' : 'dq',
  'qi' : 'qi',
  'oth' : 'oth',
} as const

export type public_rsa_web_key_type = web_key_type &  {
  n: string,
  e: string,
}
export type private_rsa_web_key_type = public_rsa_web_key_type & {
  d: string,
  p: string,
  q: string,
  dp: string,
  dq: string,
  qi: string,
  oth: string,
}

export const private_rsa_web_key_params = {
  d: "p",
  p: "p",
  q: "p",
  dp: "p",
  dq: "p",
  qi: "p",
  oth: "p",
}

/**
 * oct Parameters
 * @enum {string}
 */
export const oct_web_key  = {
  ...web_key,
  'k' : 'k',
} as const

export type private_oct_web_key_type = web_key_type & {
  k: string,
}

export const private_oct_web_key_params = {
  k: "p",
}

/**
 * OKP Parameters
 * @enum {string}
 */
export const okp_web_key  = {
  ...web_key,
  'crv' : 'crv',
  'd' : 'd',
  'x' : 'x',
} as const

export type public_okp_web_key_type = web_key_type &  {
  crv: string,
  x: string,
}
export type private_okp_web_key_type = public_okp_web_key_type & {
  d: string,
}

export const private_okp_web_key_params = {
  d: "p",
}